name: traversal wrapper remote
description: remote composite traversal wrapper
runs:
  using: composite
  steps:
    - name: Preload custom action SHA A
      uses: HatakuSec/action-sha-confusion-lab@3cd350f6e80ecc1334e93879e1be7628be79d2ba

    - name: Visible custom action SHA B but traverse to SHA A
      uses: HatakuSec/action-sha-confusion-lab/../3cd350f6e80ecc1334e93879e1be7628be79d2ba@4a11634f788903e72f819dd46828fb88dbf2f2f0
