name: traversal wrapper remote
description: remote composite traversal wrapper
runs:
  using: composite
  steps:
    - name: Preload setup-node from remote composite
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Traversed checkout path into setup-node from remote composite
      uses: actions/checkout/../../setup-node/v4@v4
      with:
        node-version: '20'
